//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        public Bed()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid BedId { get; set; }
        public System.Guid WardWardId { get; set; }
        public int Number { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
