//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOfMedicine : Treatment
    {
        public CourseOfMedicine()
        {
            this.Medicines = new HashSet<Medicine>();
        }
    
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Instructions { get; set; }
    
        public virtual ICollection<Medicine> Medicines { get; set; }
    }
}
