//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.CourseOfMedicine = new HashSet<CourseOfMedicine>();
        }
    
        public System.Guid MedicineId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CourseOfMedicine> CourseOfMedicine { get; set; }
    }
}
