//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public System.Guid NoteId { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> TreatmentTreatmentId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
