//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient : User
    {
        public Patient()
        {
            this.Visits = new HashSet<Visit>();
            this.Notes = new HashSet<Note>();
        }
    
        public string EmergencyContactName { get; set; }
        public string EmergencyContactNumber { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual WardWaitingList WardWaitingList { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
