//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffMember : User
    {
        public StaffMember()
        {
            this.TreatmentsAssigned = new List<Treatment>();
            this.TreatmentsAdministered = new List<Treatment>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLoggedIn { get; set; }
    
        public virtual List<Treatment> TreatmentsAssigned { get; set; }
        public virtual List<Treatment> TreatmentsAdministered { get; set; }
    }
}
