//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid TeamId { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual Consultant Consultant { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
