//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public System.Guid TreatmentId { get; set; }
        public System.DateTime ScheduledDate { get; set; }
    
        public virtual StaffMemeber RecordedBy { get; set; }
        public virtual StaffMemeber AdministeredBy { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
