//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.Teams = new List<Team>();
            this.Treatments = new List<Treatment>();
            this.Notes = new List<Note>();
        }
    
        public System.Guid VisitId { get; set; }
        public System.DateTime AdmittedDate { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Bed Bed { get; set; }
        public virtual List<Team> Teams { get; set; }
        public virtual List<Treatment> Treatments { get; set; }
        public virtual List<Note> Notes { get; set; }
    }
}
