//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.Teams = new HashSet<Team>();
            this.Treatments = new HashSet<Treatment>();
            this.Notes = new HashSet<Note>();
        }
    
        public System.Guid VisitId { get; set; }
        public System.DateTime AdmittedDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Bed Bed { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Treatment> Treatments { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
