//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardWaitingList
    {
        public WardWaitingList()
        {
            this.Patients = new List<Patient>();
        }
    
        public System.Guid WardWaitingListId { get; set; }
    
        public virtual Ward Ward { get; set; }
        public virtual List<Patient> Patients { get; set; }
    }
}
